
;; source files
(set @c_files     (filelist "^objc/.*\.c$"))
(set @m_files     (filelist "^objc/.*\.m$"))
(set @nu_files 	  (filelist "^nu/.*\.nu$"))
(set @frameworks  '("Cocoa" "Nu" "Carbon"))

(set @cflags "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -F/Library/Frameworks ")
(set @ldflags " -F/Library/Frameworks -framework Cocoa -framework Nu -framework Carbon -framework mach_inject_bundle")
(set @arch '("x86_64"))

(set @mflags " -fobjc-exceptions ")

;; framework description
(set @framework "NuInject")
(set @framework_identifier "nu.programming.inject")
(set @framework_creator_code "????")

(compilation-tasks)
(framework-tasks)

(task "default" => "framework")

(task "clobber" => "clean" is
      (SH "rm -rf #{@framework}.framework"))
